version: "3"
services:

  otel-collector:
    image: otel/opentelemetry-collector:0.120.0
    container_name: otel-collector
    restart: always
    user: "0:0"
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./telemetry-data.json:/etc/telemetry.json
    ports:
      - "4318:4318"